In [7]:
# -------------------------------------------------------------
# Apriori con parámetros configurables de soporte, confianza y lift
# -------------------------------------------------------------

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [8]:

# -------------------------------------------------------------
# 1. Datos de ejemplo (tus transacciones)
# -------------------------------------------------------------
transactions = [
    ["leche", "pan", "huevo"],
    ["cereal", "leche", "crema", "huevo"],
    ["leche", "crema", "pan", "huevo"]
]

In [10]:
# -------------------------------------------------------------
# 2. Parámetros configurables
# -------------------------------------------------------------
min_support = 0.6       # soporte mínimo
min_confidence = 0.6    # confianza mínima
min_lift = 1.0          # lift mínimo

print("Usando parámetros:")
print(f"min_support   = {min_support}")
print(f"min_confidence = {min_confidence}")
print(f"min_lift       = {min_lift}")

Usando parámetros:
min_support   = 0.6
min_confidence = 0.6
min_lift       = 1.0

In [11]:
# -------------------------------------------------------------
# 3. Codificación de las transacciones
# -------------------------------------------------------------
te = TransactionEncoder()
te_result = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_result, columns=te.columns_)

In [12]:
# -------------------------------------------------------------
# 4. Cálculo de los itemsets frecuentes
# -------------------------------------------------------------
frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)

print("\nItemsets frecuentes:")
display(frequent_itemsets)

Itemsets frecuentes:

     support               itemsets
0   0.666667                (crema)
1   1.000000                (huevo)
2   1.000000                (leche)
3   0.666667                  (pan)
4   0.666667         (crema, huevo)
5   0.666667         (leche, crema)
6   1.000000         (leche, huevo)
7   0.666667           (pan, huevo)
8   0.666667           (leche, pan)
9   0.666667  (leche, crema, huevo)
10  0.666667    (leche, pan, huevo)

In [13]:
# -------------------------------------------------------------
# 5. Cálculo de reglas de asociación con los parámetros
# -------------------------------------------------------------
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=min_confidence
)
# Filtro adicional por lift
rules = rules[rules["lift"] >= min_lift]

C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

In [15]:
# -------------------------------------------------------------
# 6. Mostrar las reglas resultantes
# -------------------------------------------------------------
print("\nReglas de asociación filtradas:")
rules_to_show = rules[["antecedents", "consequents", "support", "confidence", "lift"]]
display(rules_to_show)

Reglas de asociación filtradas:

       antecedents     consequents   support  confidence  lift
0          (crema)         (huevo)  0.666667    1.000000   1.0
1          (huevo)         (crema)  0.666667    0.666667   1.0
2          (leche)         (crema)  0.666667    0.666667   1.0
3          (crema)         (leche)  0.666667    1.000000   1.0
4          (leche)         (huevo)  1.000000    1.000000   1.0
5          (huevo)         (leche)  1.000000    1.000000   1.0
6            (pan)         (huevo)  0.666667    1.000000   1.0
7          (huevo)           (pan)  0.666667    0.666667   1.0
8          (leche)           (pan)  0.666667    0.666667   1.0
9            (pan)         (leche)  0.666667    1.000000   1.0
10  (leche, crema)         (huevo)  0.666667    1.000000   1.0
11  (leche, huevo)         (crema)  0.666667    0.666667   1.0
12  (crema, huevo)         (leche)  0.666667    1.000000   1.0
13         (leche)  (crema, huevo)  0.666667    0.666667   1.0
14         (crema)  (leche, huevo)  0.666667    1.000000   1.0
15         (huevo)  (leche, crema)  0.666667    0.666667   1.0
16    (leche, pan)         (huevo)  0.666667    1.000000   1.0
17  (leche, huevo)           (pan)  0.666667    0.666667   1.0
18    (pan, huevo)         (leche)  0.666667    1.000000   1.0
19         (leche)    (pan, huevo)  0.666667    0.666667   1.0
20           (pan)  (leche, huevo)  0.666667    1.000000   1.0
21         (huevo)    (leche, pan)  0.666667    0.666667   1.0